@PanoProxy_HostAddress = http://localhost:5294

GET {{PanoProxy_HostAddress}}/recorders
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

###

GET {{PanoProxy_HostAddress}}/sessions
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

###

GET {{PanoProxy_HostAddress}}/recorder/state?remoteRecorderId=00000000-0000-0000-0000-000000000000
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

###

GET {{PanoProxy_HostAddress}}/recorder/sessions?remoteRecorderId=00000000-0000-0000-0000-000000000000
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

###

POST {{PanoProxy_HostAddress}}/session/update-time?sessionId=00000000-0000-0000-0000-000000000000&newStartTime=2025-11-28T10:00:00Z&newEndTime=2025-11-28T12:00:00Z
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

###

POST {{PanoProxy_HostAddress}}/session/stop?sessionId=00000000-0000-0000-0000-000000000000
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

###

POST {{PanoProxy_HostAddress}}/session/pause?sessionId=00000000-0000-0000-0000-000000000000
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

###

POST {{PanoProxy_HostAddress}}/session/resume?sessionId=00000000-0000-0000-0000-000000000000&pauseId=00000000-0000-0000-0000-000000000000&pauseStartTime=2025-12-05T10:58:15Z
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

###

POST {{PanoProxy_HostAddress}}/session/start?sessionId=00000000-0000-0000-0000-000000000000
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

###

POST {{PanoProxy_HostAddress}}/session/create?remoteRecorderId=00000000-0000-0000-0000-000000000000&sessionName=Und%20noch%20eine%20Aufname&startTime=2026-01-21T15:20:00Z&duration=00:05:00
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

# Disconected, Stopped