//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoProxy.Auth
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationInfo", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class AuthenticationInfo : object
    {
        
        private string AuthCodeField;
        
        private string PasswordField;
        
        private string UserKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode
        {
            get
            {
                return this.AuthCodeField;
            }
            set
            {
                this.AuthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PanoProxy.Auth.IAuth")]
    public interface IAuth
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/LogOnWithPassword", ReplyAction="http://tempuri.org/IAuth/LogOnWithPasswordResponse")]
        bool LogOnWithPassword(string userKey, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/LogOnWithPassword", ReplyAction="http://tempuri.org/IAuth/LogOnWithPasswordResponse")]
        System.Threading.Tasks.Task<bool> LogOnWithPasswordAsync(string userKey, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/LogOnWithExternalProvider", ReplyAction="http://tempuri.org/IAuth/LogOnWithExternalProviderResponse")]
        bool LogOnWithExternalProvider(string userKey, string authCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/LogOnWithExternalProvider", ReplyAction="http://tempuri.org/IAuth/LogOnWithExternalProviderResponse")]
        System.Threading.Tasks.Task<bool> LogOnWithExternalProviderAsync(string userKey, string authCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/GetServerVersion", ReplyAction="http://tempuri.org/IAuth/GetServerVersionResponse")]
        string GetServerVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/GetServerVersion", ReplyAction="http://tempuri.org/IAuth/GetServerVersionResponse")]
        System.Threading.Tasks.Task<string> GetServerVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/GetAuthenticatedUrl", ReplyAction="http://tempuri.org/IAuth/GetAuthenticatedUrlResponse")]
        string GetAuthenticatedUrl(PanoProxy.Auth.AuthenticationInfo auth, string targetUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/GetAuthenticatedUrl", ReplyAction="http://tempuri.org/IAuth/GetAuthenticatedUrlResponse")]
        System.Threading.Tasks.Task<string> GetAuthenticatedUrlAsync(PanoProxy.Auth.AuthenticationInfo auth, string targetUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/ReportIntegrationInfo", ReplyAction="http://tempuri.org/IAuth/ReportIntegrationInfoResponse")]
        void ReportIntegrationInfo(PanoProxy.Auth.AuthenticationInfo auth, string idProviderName, string moduleVersion, string targetPlatformVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/ReportIntegrationInfo", ReplyAction="http://tempuri.org/IAuth/ReportIntegrationInfoResponse")]
        System.Threading.Tasks.Task ReportIntegrationInfoAsync(PanoProxy.Auth.AuthenticationInfo auth, string idProviderName, string moduleVersion, string targetPlatformVersion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IAuthChannel : PanoProxy.Auth.IAuth, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AuthClient : System.ServiceModel.ClientBase<PanoProxy.Auth.IAuth>, PanoProxy.Auth.IAuth
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthClient.GetBindingForEndpoint(endpointConfiguration), AuthClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool LogOnWithPassword(string userKey, string password)
        {
            return base.Channel.LogOnWithPassword(userKey, password);
        }
        
        public System.Threading.Tasks.Task<bool> LogOnWithPasswordAsync(string userKey, string password)
        {
            return base.Channel.LogOnWithPasswordAsync(userKey, password);
        }
        
        public bool LogOnWithExternalProvider(string userKey, string authCode)
        {
            return base.Channel.LogOnWithExternalProvider(userKey, authCode);
        }
        
        public System.Threading.Tasks.Task<bool> LogOnWithExternalProviderAsync(string userKey, string authCode)
        {
            return base.Channel.LogOnWithExternalProviderAsync(userKey, authCode);
        }
        
        public string GetServerVersion()
        {
            return base.Channel.GetServerVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetServerVersionAsync()
        {
            return base.Channel.GetServerVersionAsync();
        }
        
        public string GetAuthenticatedUrl(PanoProxy.Auth.AuthenticationInfo auth, string targetUrl)
        {
            return base.Channel.GetAuthenticatedUrl(auth, targetUrl);
        }
        
        public System.Threading.Tasks.Task<string> GetAuthenticatedUrlAsync(PanoProxy.Auth.AuthenticationInfo auth, string targetUrl)
        {
            return base.Channel.GetAuthenticatedUrlAsync(auth, targetUrl);
        }
        
        public void ReportIntegrationInfo(PanoProxy.Auth.AuthenticationInfo auth, string idProviderName, string moduleVersion, string targetPlatformVersion)
        {
            base.Channel.ReportIntegrationInfo(auth, idProviderName, moduleVersion, targetPlatformVersion);
        }
        
        public System.Threading.Tasks.Task ReportIntegrationInfoAsync(PanoProxy.Auth.AuthenticationInfo auth, string idProviderName, string moduleVersion, string targetPlatformVersion)
        {
            return base.Channel.ReportIntegrationInfoAsync(auth, idProviderName, moduleVersion, targetPlatformVersion);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuth))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuth1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuth))
            {
                return new System.ServiceModel.EndpointAddress("https://unibas-test.cloud.panopto.eu/Panopto/PublicAPI/4.6/Auth.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuth1))
            {
                return new System.ServiceModel.EndpointAddress("http://unibas-test.cloud.panopto.eu/Panopto/PublicAPI/4.6/Auth.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAuth,
            
            BasicHttpBinding_IAuth1,
        }
    }
}
