//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoProxy.RemoteRecorderManagement
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationInfo", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class AuthenticationInfo : object
    {
        
        private string AuthCodeField;
        
        private string PasswordField;
        
        private string UserKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode
        {
            get
            {
                return this.AuthCodeField;
            }
            set
            {
                this.AuthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteRecorder", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V42.Soa" +
        "p")]
    public partial class RemoteRecorder : object
    {
        
        private PanoProxy.RemoteRecorderManagement.RemoteRecorderDevice[] DevicesField;
        
        private string ExternalIdField;
        
        private System.Guid IdField;
        
        private string MachineIPField;
        
        private string NameField;
        
        private string PreviewUrlField;
        
        private System.Guid[] ScheduledRecordingsField;
        
        private string SettingsUrlField;
        
        private PanoProxy.RemoteRecorderManagement.RemoteRecorderState StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoProxy.RemoteRecorderManagement.RemoteRecorderDevice[] Devices
        {
            get
            {
                return this.DevicesField;
            }
            set
            {
                this.DevicesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineIP
        {
            get
            {
                return this.MachineIPField;
            }
            set
            {
                this.MachineIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviewUrl
        {
            get
            {
                return this.PreviewUrlField;
            }
            set
            {
                this.PreviewUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] ScheduledRecordings
        {
            get
            {
                return this.ScheduledRecordingsField;
            }
            set
            {
                this.ScheduledRecordingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettingsUrl
        {
            get
            {
                return this.SettingsUrlField;
            }
            set
            {
                this.SettingsUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoProxy.RemoteRecorderManagement.RemoteRecorderState State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteRecorderDevice", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class RemoteRecorderDevice : object
    {
        
        private PanoProxy.RemoteRecorderManagement.RemoteRecorderDeviceType DeviceTypeField;
        
        private bool IsCapturingField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoProxy.RemoteRecorderManagement.RemoteRecorderDeviceType DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCapturing
        {
            get
            {
                return this.IsCapturingField;
            }
            set
            {
                this.IsCapturingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteRecorderState", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum RemoteRecorderState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stopped = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Previewing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Recording = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paused = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faulted = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disconnected = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteRecorderDeviceType", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum RemoteRecorderDeviceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DV = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HDV = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Video = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Audio = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Screen = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Slide = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagination", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class Pagination : object
    {
        
        private int MaxNumberResultsField;
        
        private int PageNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumberResults
        {
            get
            {
                return this.MaxNumberResultsField;
            }
            set
            {
                this.MaxNumberResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecorderSortField", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum RecorderSortField : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Name = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        State = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListRecordersResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V42.Soa" +
        "p")]
    public partial class ListRecordersResponse : object
    {
        
        private PanoProxy.RemoteRecorderManagement.RemoteRecorder[] PagedResultsField;
        
        private int TotalResultCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoProxy.RemoteRecorderManagement.RemoteRecorder[] PagedResults
        {
            get
            {
                return this.PagedResultsField;
            }
            set
            {
                this.PagedResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalResultCount
        {
            get
            {
                return this.TotalResultCountField;
            }
            set
            {
                this.TotalResultCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecorderSettings", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class RecorderSettings : object
    {
        
        private System.Guid RecorderIdField;
        
        private bool SuppressPrimaryField;
        
        private bool SuppressSecondaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RecorderId
        {
            get
            {
                return this.RecorderIdField;
            }
            set
            {
                this.RecorderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuppressPrimary
        {
            get
            {
                return this.SuppressPrimaryField;
            }
            set
            {
                this.SuppressPrimaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuppressSecondary
        {
            get
            {
                return this.SuppressSecondaryField;
            }
            set
            {
                this.SuppressSecondaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduledRecordingResult", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V42.Soa" +
        "p")]
    public partial class ScheduledRecordingResult : object
    {
        
        private PanoProxy.RemoteRecorderManagement.ScheduledRecordingInfo[] ConflictingSessionsField;
        
        private bool ConflictsExistField;
        
        private System.Guid[] SessionIDsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoProxy.RemoteRecorderManagement.ScheduledRecordingInfo[] ConflictingSessions
        {
            get
            {
                return this.ConflictingSessionsField;
            }
            set
            {
                this.ConflictingSessionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ConflictsExist
        {
            get
            {
                return this.ConflictsExistField;
            }
            set
            {
                this.ConflictsExistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] SessionIDs
        {
            get
            {
                return this.SessionIDsField;
            }
            set
            {
                this.SessionIDsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduledRecordingInfo", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V42.Soa" +
        "p")]
    public partial class ScheduledRecordingInfo : object
    {
        
        private System.DateTime EndTimeField;
        
        private System.Guid SessionIDField;
        
        private string SessionNameField;
        
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionID
        {
            get
            {
                return this.SessionIDField;
            }
            set
            {
                this.SessionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionName
        {
            get
            {
                return this.SessionNameField;
            }
            set
            {
                this.SessionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DayOfWeek", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public enum DayOfWeek : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sunday = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monday = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tuesday = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wednesday = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thursday = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friday = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saturday = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PanoProxy.RemoteRecorderManagement.IRemoteRecorderManagement")]
    public interface IRemoteRecorderManagement
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/GetRemoteRecordersById", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/GetRemoteRecordersByIdResponse")]
        PanoProxy.RemoteRecorderManagement.RemoteRecorder[] GetRemoteRecordersById(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid[] remoteRecorderIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/GetRemoteRecordersById", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/GetRemoteRecordersByIdResponse")]
        System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.RemoteRecorder[]> GetRemoteRecordersByIdAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid[] remoteRecorderIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/GetRemoteRecordersByExternalId", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/GetRemoteRecordersByExternalIdRespon" +
            "se")]
        PanoProxy.RemoteRecorderManagement.RemoteRecorder[] GetRemoteRecordersByExternalId(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, string[] externalIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/GetRemoteRecordersByExternalId", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/GetRemoteRecordersByExternalIdRespon" +
            "se")]
        System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.RemoteRecorder[]> GetRemoteRecordersByExternalIdAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, string[] externalIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/UpdateRemoteRecorderExternalId", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/UpdateRemoteRecorderExternalIdRespon" +
            "se")]
        void UpdateRemoteRecorderExternalId(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId, string externalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/UpdateRemoteRecorderExternalId", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/UpdateRemoteRecorderExternalIdRespon" +
            "se")]
        System.Threading.Tasks.Task UpdateRemoteRecorderExternalIdAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId, string externalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/ListRecorders", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/ListRecordersResponse")]
        PanoProxy.RemoteRecorderManagement.ListRecordersResponse ListRecorders(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, PanoProxy.RemoteRecorderManagement.Pagination pagination, PanoProxy.RemoteRecorderManagement.RecorderSortField sortBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/ListRecorders", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/ListRecordersResponse")]
        System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.ListRecordersResponse> ListRecordersAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, PanoProxy.RemoteRecorderManagement.Pagination pagination, PanoProxy.RemoteRecorderManagement.RecorderSortField sortBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/ScheduleRecording", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/ScheduleRecordingResponse")]
        PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult ScheduleRecording(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, string name, System.Guid folderId, bool isBroadcast, System.DateTime start, System.DateTime end, PanoProxy.RemoteRecorderManagement.RecorderSettings[] recorderSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/ScheduleRecording", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/ScheduleRecordingResponse")]
        System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult> ScheduleRecordingAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, string name, System.Guid folderId, bool isBroadcast, System.DateTime start, System.DateTime end, PanoProxy.RemoteRecorderManagement.RecorderSettings[] recorderSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/ScheduleRecurringRecording", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/ScheduleRecurringRecordingResponse")]
        PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult ScheduleRecurringRecording(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid scheduledSessionId, PanoProxy.RemoteRecorderManagement.DayOfWeek[] daysOfWeek, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/ScheduleRecurringRecording", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/ScheduleRecurringRecordingResponse")]
        System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult> ScheduleRecurringRecordingAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid scheduledSessionId, PanoProxy.RemoteRecorderManagement.DayOfWeek[] daysOfWeek, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/UpdateRecordingTime", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/UpdateRecordingTimeResponse")]
        PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult UpdateRecordingTime(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid sessionId, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/UpdateRecordingTime", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/UpdateRecordingTimeResponse")]
        System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult> UpdateRecordingTimeAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid sessionId, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/UpdateRecordingSettings", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/UpdateRecordingSettingsResponse")]
        PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult UpdateRecordingSettings(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid sessionId, PanoProxy.RemoteRecorderManagement.RecorderSettings[] recorderSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/UpdateRecordingSettings", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/UpdateRecordingSettingsResponse")]
        System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult> UpdateRecordingSettingsAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid sessionId, PanoProxy.RemoteRecorderManagement.RecorderSettings[] recorderSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/GetDefaultFolderForRecorder", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/GetDefaultFolderForRecorderResponse")]
        System.Guid GetDefaultFolderForRecorder(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/GetDefaultFolderForRecorder", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/GetDefaultFolderForRecorderResponse")]
        System.Threading.Tasks.Task<System.Guid> GetDefaultFolderForRecorderAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/GetMachineSidForRecorder", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/GetMachineSidForRecorderResponse")]
        string GetMachineSidForRecorder(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRecorderManagement/GetMachineSidForRecorder", ReplyAction="http://tempuri.org/IRemoteRecorderManagement/GetMachineSidForRecorderResponse")]
        System.Threading.Tasks.Task<string> GetMachineSidForRecorderAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IRemoteRecorderManagementChannel : PanoProxy.RemoteRecorderManagement.IRemoteRecorderManagement, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class RemoteRecorderManagementClient : System.ServiceModel.ClientBase<PanoProxy.RemoteRecorderManagement.IRemoteRecorderManagement>, PanoProxy.RemoteRecorderManagement.IRemoteRecorderManagement
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RemoteRecorderManagementClient(EndpointConfiguration endpointConfiguration) : 
                base(RemoteRecorderManagementClient.GetBindingForEndpoint(endpointConfiguration), RemoteRecorderManagementClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteRecorderManagementClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RemoteRecorderManagementClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteRecorderManagementClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RemoteRecorderManagementClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteRecorderManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PanoProxy.RemoteRecorderManagement.RemoteRecorder[] GetRemoteRecordersById(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid[] remoteRecorderIds)
        {
            return base.Channel.GetRemoteRecordersById(auth, remoteRecorderIds);
        }
        
        public System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.RemoteRecorder[]> GetRemoteRecordersByIdAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid[] remoteRecorderIds)
        {
            return base.Channel.GetRemoteRecordersByIdAsync(auth, remoteRecorderIds);
        }
        
        public PanoProxy.RemoteRecorderManagement.RemoteRecorder[] GetRemoteRecordersByExternalId(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, string[] externalIds)
        {
            return base.Channel.GetRemoteRecordersByExternalId(auth, externalIds);
        }
        
        public System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.RemoteRecorder[]> GetRemoteRecordersByExternalIdAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, string[] externalIds)
        {
            return base.Channel.GetRemoteRecordersByExternalIdAsync(auth, externalIds);
        }
        
        public void UpdateRemoteRecorderExternalId(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId, string externalId)
        {
            base.Channel.UpdateRemoteRecorderExternalId(auth, remoteRecorderId, externalId);
        }
        
        public System.Threading.Tasks.Task UpdateRemoteRecorderExternalIdAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId, string externalId)
        {
            return base.Channel.UpdateRemoteRecorderExternalIdAsync(auth, remoteRecorderId, externalId);
        }
        
        public PanoProxy.RemoteRecorderManagement.ListRecordersResponse ListRecorders(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, PanoProxy.RemoteRecorderManagement.Pagination pagination, PanoProxy.RemoteRecorderManagement.RecorderSortField sortBy)
        {
            return base.Channel.ListRecorders(auth, pagination, sortBy);
        }
        
        public System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.ListRecordersResponse> ListRecordersAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, PanoProxy.RemoteRecorderManagement.Pagination pagination, PanoProxy.RemoteRecorderManagement.RecorderSortField sortBy)
        {
            return base.Channel.ListRecordersAsync(auth, pagination, sortBy);
        }
        
        public PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult ScheduleRecording(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, string name, System.Guid folderId, bool isBroadcast, System.DateTime start, System.DateTime end, PanoProxy.RemoteRecorderManagement.RecorderSettings[] recorderSettings)
        {
            return base.Channel.ScheduleRecording(auth, name, folderId, isBroadcast, start, end, recorderSettings);
        }
        
        public System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult> ScheduleRecordingAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, string name, System.Guid folderId, bool isBroadcast, System.DateTime start, System.DateTime end, PanoProxy.RemoteRecorderManagement.RecorderSettings[] recorderSettings)
        {
            return base.Channel.ScheduleRecordingAsync(auth, name, folderId, isBroadcast, start, end, recorderSettings);
        }
        
        public PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult ScheduleRecurringRecording(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid scheduledSessionId, PanoProxy.RemoteRecorderManagement.DayOfWeek[] daysOfWeek, System.DateTime end)
        {
            return base.Channel.ScheduleRecurringRecording(auth, scheduledSessionId, daysOfWeek, end);
        }
        
        public System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult> ScheduleRecurringRecordingAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid scheduledSessionId, PanoProxy.RemoteRecorderManagement.DayOfWeek[] daysOfWeek, System.DateTime end)
        {
            return base.Channel.ScheduleRecurringRecordingAsync(auth, scheduledSessionId, daysOfWeek, end);
        }
        
        public PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult UpdateRecordingTime(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid sessionId, System.DateTime start, System.DateTime end)
        {
            return base.Channel.UpdateRecordingTime(auth, sessionId, start, end);
        }
        
        public System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult> UpdateRecordingTimeAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid sessionId, System.DateTime start, System.DateTime end)
        {
            return base.Channel.UpdateRecordingTimeAsync(auth, sessionId, start, end);
        }
        
        public PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult UpdateRecordingSettings(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid sessionId, PanoProxy.RemoteRecorderManagement.RecorderSettings[] recorderSettings)
        {
            return base.Channel.UpdateRecordingSettings(auth, sessionId, recorderSettings);
        }
        
        public System.Threading.Tasks.Task<PanoProxy.RemoteRecorderManagement.ScheduledRecordingResult> UpdateRecordingSettingsAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid sessionId, PanoProxy.RemoteRecorderManagement.RecorderSettings[] recorderSettings)
        {
            return base.Channel.UpdateRecordingSettingsAsync(auth, sessionId, recorderSettings);
        }
        
        public System.Guid GetDefaultFolderForRecorder(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId)
        {
            return base.Channel.GetDefaultFolderForRecorder(auth, remoteRecorderId);
        }
        
        public System.Threading.Tasks.Task<System.Guid> GetDefaultFolderForRecorderAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId)
        {
            return base.Channel.GetDefaultFolderForRecorderAsync(auth, remoteRecorderId);
        }
        
        public string GetMachineSidForRecorder(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId)
        {
            return base.Channel.GetMachineSidForRecorder(auth, remoteRecorderId);
        }
        
        public System.Threading.Tasks.Task<string> GetMachineSidForRecorderAsync(PanoProxy.RemoteRecorderManagement.AuthenticationInfo auth, System.Guid remoteRecorderId)
        {
            return base.Channel.GetMachineSidForRecorderAsync(auth, remoteRecorderId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRemoteRecorderManagement))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRemoteRecorderManagement1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRemoteRecorderManagement))
            {
                return new System.ServiceModel.EndpointAddress("https://unibas-test.cloud.panopto.eu/Panopto/publicapi/4.6/RemoteRecorderManageme" +
                        "nt.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRemoteRecorderManagement1))
            {
                return new System.ServiceModel.EndpointAddress("http://unibas-test.cloud.panopto.eu/Panopto/publicapi/4.6/RemoteRecorderManagemen" +
                        "t.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRemoteRecorderManagement,
            
            BasicHttpBinding_IRemoteRecorderManagement1,
        }
    }
}
